name: Build alt-ime-ahk (v1) to EXE

on:
  workflow_dispatch: {}
  push:
    paths:
      - "alt-ime-ahk.ahk"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Chocolatey で AutoHotkey v1 portable をインストール
      - name: Install AutoHotkey v1 portable via Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install autohotkey.portable --version=1.1.36.02 -y

      # Ahk2Exe のパスを探して .ahk → .exe に変換
      - name: Compile to EXE with Ahk2Exe
        shell: pwsh
        run: |
          $pkg = Get-ChildItem 'C:\ProgramData\chocolatey\lib' -Filter 'autohotkey*' | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          $compiler = Join-Path $pkg.FullName 'tools\Compiler\Ahk2Exe.exe'
          $baseBin  = Join-Path $pkg.FullName 'tools\Compiler\Unicode 64-bit.bin'
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          & $compiler /in "alt-ime-ahk.ahk" /out "dist\alt-ime-ahk.exe" /base "$baseBin"
          Write-Host "Built: dist\alt-ime-ahk.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alt-ime-ahk-exe
          path: dist/alt-ime-ahk.exe
          if-no-files-found: error
